version: "3.5"
services:
  mysqlservice:
    image: mysql:5.5
    ports:
      - 3306:3306
    container_name: mysql-container
    network_mode: host
    hostname: localhost
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root123
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  mongodbservice:
    image: mongo:latest
    container_name: mongo-container
    network_mode: host
    hostname: localhost
    ports:
      - 27017:27017

  userauthenticationproject:
    container_name: user-authentication-project
    build: UserAuthenticationProject/
    hostname: localhost
    network_mode: host
    ports:
      - 8085:8085
    depends_on:
      - mysqlservice
      - eurekaServer
      - cloudapiservice
    restart: always

  kanbanservice:
    container_name: kanban-service
    build: KanbanService/
    hostname: localhost
    network_mode: host
    ports:
      - 8082:8082
    depends_on:
      - mongodbservice
      - eurekaServer
      - cloudapiservice
      - kanbantaskmanager
      - userauthenticationproject
    restart: always

  kanbantaskmanager:
    container_name: kanban-task-manager
    build: kanbantaskmanager/
    hostname: localhost
    network_mode: host
    ports:
      - 8086:8086
    depends_on:
      - mongodbservice
      - eurekaServer
      - cloudapiservice
    restart: always

  notificationservice:
    container_name: notification-service
    build: notification-service/
    hostname: localhost
    network_mode: host
    ports:
      - 8084:8084
    depends_on:
      - mongodbservice
      - eurekaServer
      - cloudapiservice

  cloudapiservice:
    image: cloud-api-service
    build: ApiGateWay/
    restart: always
    network_mode: host
    #hostname: localhost
    ports:
      - 9000:9000
    environment:
      API_GATEWAY_PORT: 9000
      EUREKA_SERVER_IP: localhost
      EUREKA_SERVER_PORT: 8761
    depends_on:
      - eurekaServer


  eurekaServer:
    image: eureka-service
    build: EurekaServer/
    restart: always
    network_mode: host
    #hostname: localhost
    environment:
      EUREKA_SERVER_PORT: 8761
    ports:
      - 8761:8761
